[package]
name = "dataset-cleaning"
version = "0.1.0"
edition = "2021"

[dependencies]
component-structure = { path = "../component-structure" }
csv = "1.3.0"
once_cell = "1.19.0"
rand = "0.8.5"
regex = "1.10.4"
serde = { version = "1.0.199", features = ["derive"] }
serde_json = "1.0.116"
